[package]
name = "iced-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["debug", "tokio", "highlighter"] }
rfd = "0.14.0"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["fs", "rt"] }
